#region Vars
    #region Description
        $ProjectName = Read-Host -Prompt 'Input your RSDK Project name'
        $ObjectName = Read-Host -Prompt 'Input the Object name'
        $User = Read-Host -Prompt 'Input your user name'
		$AliasesInput = Read-Host -Prompt 'How many aliases? (Max is 47)'
    #endregion Description

    #region setup   
        $SpriteSheet = "Global/Display.gif"
        $Aliases = 0
        $FileName = ".\$ObjectName" + ".txt"
    #endregion setup
#endregion Vars

$FileExists = Test-Path -Path $FileName -PathType Leaf

#region Code
If($FileExists) # Is there a file with the same name in the same folder?
{
    Write-Error "$FileName already exists"
    # Exit # Stops the script.

}
Else # It doesn't exist yet.
{
#region RSDKv4            
    Write-Host Generating Script
    # make a file
    New-Item -ItemType File -Name $FileName -ErrorAction SilentlyContinue | Out-Null
    # Put all of this in it
    Add-Content $FileName -Value "// ----------------------------------"
    Add-Content $FileName -Value "// RSDK Project:  $ProjectName"
    Add-Content $FileName -Value "// Script Description:    $ObjectName Object "
    Add-Content $FileName -Value "// Script Author: $User"
    Add-Content $FileName -Value "// Generated by Twanvanb1's script generator"
    Add-Content $FileName -Value "// ----------------------------------"
    Add-Content $FileName -Value "" 
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Aliases"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    while($Aliases -le $AliasesInput)
    {
        Add-Content $FileName -Value "private alias object.value$Aliases 	:"
        $Aliases++
    }
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Function Declarations"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Static Values"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Tables"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Function Definitions"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Events"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "event ObjectUpdate"
    Add-Content $FileName -Value "end event"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "event ObjectDraw"
    Add-Content $FileName -Value "end event"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "event ObjectStartup"
    Add-Content $FileName -Value "end event"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value "// Editor Events"
    Add-Content $FileName -Value "// ========================"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "event RSDKDraw"
    Add-Content $FileName -Value "  DrawSprite(0)"
    Add-Content $FileName -Value "end event"
    Add-Content $FileName -Value ""
    Add-Content $FileName -Value "event RSDKLoad"
    Add-Content $FileName -Value "  LoadSpriteSheet($SpriteSheet)"
    Add-Content $FileName -Value "  SpriteFrame(-16, -16, 32, 32, 1, 143)"
    Add-Content $FileName -Value "end event"
#endregion RSDKv4
   
}

Code $FileName # Open in Visual Studio Code
#notepad++ $FileName # Open in notepad++